version: '3.8'
services:
  postgres:
      image: postgres:latest
      container_name: postgres_container
      ports:
        - 5440:5432
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      volumes:
        - postgres-volume:/var/lib/postgresql/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
        - mynetworks
      hostname: postgres
  
  flaskapi:
      build:
        context: ./api
        dockerfile: Dockerfile
      container_name: flask_container
      environment:
        - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}      
        - SECRET_KEY=${SECRET_KEY}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - VUE_BASE_URL=${VUE_BASE_URL}
      volumes:
        - ./api:/app
      ports:
        - 8000:8000
      depends_on:
        - postgres
      networks:
        - mynetworks
      hostname: flaskapi
  
  vueclient:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: vue_container
      environment:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      ports:
        - 4173:4173
      depends_on:
        - flaskapi
      networks:
        - mynetworks
      hostname: vueclient

volumes:
  postgres-volume:

networks:
  mynetworks: