version: '3.8'
services:
    
  postgres:
      build:
        context: ./postgres
        dockerfile: Dockerfile
      container_name: postgres_container
      ports:
        - 5440:5432
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      hostname: postgres
      volumes:
        - postgres-volume:/var/lib/postgresql/data
      networks:
        - mynetworks
  
  flaskapi:
      build:
        context: ./api
        dockerfile: Dockerfile
      container_name: flask_container
      environment:
        - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}      
        - SECRET_KEY=${SECRET_KEY}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - VUE_BASE_URL=${VUE_BASE_URL}
      hostname: flaskapi
      ports:
        - 8000:8000
      depends_on:
        - postgres
      networks:
        - mynetworks
  
  vueclient:
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      container_name: vue_container
      hostname: vueclient
      ports:
        - 4173:4173
      depends_on:
        - flaskapi
      networks:
        - mynetworks

volumes:
  postgres-volume:

networks:
  mynetworks: