version: '3.8'
services:
  minio:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: minio_container
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    hostname: minio
    volumes:
      - minio-data:/mnt/data
    networks:
      - mynetworks
    
  postgres:
      build:
        context: ./postgres
        dockerfile: Dockerfile
      container_name: postgres_container
      ports:
        - 5440:5432
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      hostname: postgres
      volumes:
        - postgres-volume:/var/lib/postgresql/data
      depends_on:
        - minio
      networks:
        - mynetworks
  
  flaskapi:
      build:
        context: ./api
        dockerfile: Dockerfile
      container_name: flask_container
      environment:
        - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}      
        - SECRET_KEY=${SECRET_KEY}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - VUE_BASE_URL=${VUE_BASE_URL}
        - MINIO_URL=${MINIO_URL}
        - MINIO_ROOT_USER=${MINIO_ROOT_USER}
        - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      hostname: flaskapi
      volumes:
        - ./api:/app
      ports:
        - 8000:8000
      depends_on:
        - postgres
      networks:
        - mynetworks
  
  vueclient:
      build:
        context: ./frontend
        dockerfile: Dockerfile
        args:
          - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      container_name: vue_container
      hostname: vueclient
      ports:
        - 4173:4173
      depends_on:
        - flaskapi
      networks:
        - mynetworks

volumes:
  postgres-volume:
  minio-data:

networks:
  mynetworks: