version: '3.8'
services:
    
  postgres:
      image: naputami/postgres:latest
      container_name: postgres_container
      ports:
        - 5440:5432
      env_file:
        - .env
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      hostname: postgres
      volumes:
        - postgres-volume:/var/lib/postgresql/data
      networks:
        - mynetworks
  
  flaskapi:
      image: naputami/flaskapi:latest
      container_name: flask_container
      env_file:
        - .env
      environment:
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}      
        - SECRET_KEY=${SECRET_KEY}
        - MINIO_BUCKET=${MINIO_BUCKET}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      hostname: flaskapi
      ports:
        - 8000:8000
      depends_on:
        - postgres
      networks:
        - mynetworks
  
  vueclient:
      image: naputami/vueclient:latest
      container_name: vue_container
      hostname: vueclient
      ports:
        - 4173:4173
      depends_on:
        - flaskapi
      networks:
        - mynetworks

volumes:
  postgres-volume:

networks:
  mynetworks:
