name: CI (Continue Integrations)

on: 
  pull_request:
    branches:
      - main


jobs:


    build-testing:
        name: Build and Testing
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
              with:
                  ref: main
                  
            - name: Create .env file
              run: |
                 echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
                 echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
                 echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
                 echo "MINIO_BUCKET=${{ secrets.MINIO_BUCKET }}" >> .env
                 echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
                 echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
                 
            - name: Install Docker Compose
              run: |
                sudo apt-get update
                sudo apt-get install -y docker-compose

            - name: Build and Run Container
              run: |
                sudo docker compose pull && sudo docker compose --env-file .env up -d

            - name: Install requirements for testing
              run: |
                pip install -r testing/requirements.txt

            - name: Testing
              run: |
                sleep 20
                pytest testing/test.py
